name: Build ANE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Apache Ant
      run: |
        sudo apt-get update
        sudo apt-get install ant

    - name: Build ANE
      run: ant -f build/build.xml # Adjust the path to your build.xml file

    - name: Find ANE file
      id: find-ane
      run: |
        find . -type f -name '*.ane' -print0 | xargs -0 echo "::set-output name=ane-path::"

    - name: Upload ANE artifact
      if: steps.find-ane.outputs.ane-path != ''
      uses: actions/upload-artifact@v2
      with:
        name: share-ane-artifact
        path: ${{ steps.find-ane.outputs.ane-path }}
